modLoader="javafml"
loaderVersion="[47,)"
license="CC-BY-NC-4.0"

[[mods]]
modId="endless_deep_space"
version="0.9.8"
displayName="Endless Deep Space"
displayURL="https://space.bilibili.com/375078257"
logoFile="logo.png"
credits="\u662F\u5982\u68A6\u5440rumeng2233"
authors="\u662F\u5982\u68A6\u5440rumeng2233"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.endless_deep_space]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.endless_deep_space]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration